//
//  HTTPError.swift
//  SearchTwitter
//
//  Created by Isha Dua on 04/10/21.
//

import Foundation

/// Errors that will be generated by the HTTPManager
enum HTTPError: Error {
    case invalidURL
    case noInternet
    case invalidResponse(Data?, URLResponse?)
}
